# Generated by Django 2.1.7 on 2019-03-14 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arithmetic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('which_angel', models.CharField(max_length=20)),
                ('body', models.CharField(max_length=100)),
                ('answer', models.IntegerField()),
                ('score', models.BooleanField()),
                ('elapsed_time', models.CharField(max_length=10)),
                ('results', models.IntegerField()),
                ('operation', models.CharField(max_length=3)),
                ('date', models.CharField(max_length=30)),
            ],
        ),
    ]
