# Generated by Django 2.1.7 on 2019-03-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MathSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('which_angel', models.CharField(max_length=20)),
                ('wrong', models.IntegerField()),
                ('right', models.IntegerField()),
                ('total', models.IntegerField()),
                ('date', models.DateField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='arithmetic',
            name='date',
            field=models.DateField(max_length=30),
        ),
    ]
