# Generated by Django 2.2 on 2019-04-08 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190314_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateProblems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene', models.CharField(max_length=20)),
                ('background', models.CharField(max_length=100)),
                ('quantifier', models.CharField(max_length=20)),
                ('obj', models.CharField(max_length=20)),
                ('activity', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=100)),
                ('n1', models.IntegerField()),
                ('n2', models.IntegerField()),
                ('op', models.CharField(max_length=10)),
                ('res', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene', models.CharField(max_length=20)),
                ('body', models.CharField(max_length=100)),
                ('n1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='num1', to='login.GenerateProblems')),
                ('n2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='num2', to='login.GenerateProblems')),
                ('op', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation', to='login.GenerateProblems')),
                ('res', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='login.GenerateProblems')),
            ],
        ),
    ]
