# Generated by Django 2.2 on 2019-04-12 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20190412_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problems',
            name='n1',
        ),
        migrations.RemoveField(
            model_name='problems',
            name='n2',
        ),
        migrations.RemoveField(
            model_name='problems',
            name='op',
        ),
        migrations.RemoveField(
            model_name='problems',
            name='res',
        ),
        migrations.RemoveField(
            model_name='problems',
            name='scene',
        ),
        migrations.AddField(
            model_name='problems',
            name='answer',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='problems',
            name='date',
            field=models.DateField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='problems',
            name='elapsed_time',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='problems',
            name='operation',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='problems',
            name='problem',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.GenerateProblems'),
        ),
        migrations.AddField(
            model_name='problems',
            name='results',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='problems',
            name='score',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='problems',
            name='which_angel',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
