# Generated by Django 2.2 on 2019-04-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20190412_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='answer',
            field=models.IntegerField(null=True),
        ),
    ]
